---
blueprint:
  name: AWTRIX Solar Energy Monitor (AWTRIX 3) – W/kW + custom refresh + notify/app
  description: >
    Okresowo pokazuje bieżącą moc PV na AWTRIX 3.
    Wybierz tryb wyświetlania: powiadomienie (notify, jednorazowy popup) lub krótka aplikacja (app) z krótkim lifetime.
    Ikony: 54156 (zielony), 50557 (biały dyn), 50546 (statyczny).

  domain: automation
  input:
    awtrix:
      name: AWTRIX Device
      description: Wybierz swoje urządzenie AWTRIX 3 (MQTT)
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    power_source:
      name: Power Sensor
      description: Sensor mocy z instalacji PV.
      selector:
        entity:
          domain: [sensor]
          multiple: false

    sensor_unit:
      name: Sensor unit
      description: W jakich jednostkach podaje wartość Twój sensor?
      selector:
        select:
          options: [W, kW]
      default: W

    threshold_high:
      name: Threshold for high solar production (W)
      description: Próg dla „wysokiej” produkcji (w W).
      selector:
        number: {min: 0, max: 100000, unit_of_measurement: W, mode: slider}
      default: 400

    threshold_low:
      name: Threshold for low solar production (W)
      description: Próg dla „niskiej” produkcji (w W).
      selector:
        number: {min: 0, max: 100000, unit_of_measurement: W, mode: slider}
      default: 100

    skip_if_zero_watts:
      name: Hide when 0 W
      description: Nie wysyłaj na AWTRIX, gdy moc = 0 W.
      selector: {boolean:}
      default: false

    skip_during_night_hours:
      name: Hide during night time
      description: Nie wysyłaj w godzinach nocnych.
      selector: {boolean:}
      default: false

    night_starts_after_time:
      name: Night start
      description: Godzina rozpoczęcia „nocy”.
      default: "00:00:00"
      selector: {time: {}}

    night_ends_after_time:
      name: Night end
      description: Godzina zakończenia „nocy”.
      default: "00:00:00"
      selector: {time: {}}

    refresh_minutes:
      name: Refresh pattern (minutes)
      description: |
        Wzór dla pola `minutes:` w time_pattern.
        Przykłady:
        - "/5"  → co 5 minut
        - "0,15,30,45" → o podanych minutach każdej godziny
      selector: {text: {multiline: false}}
      default: "/5"

    display_mode:
      name: Display mode
      description: 'notify = popup jednorazowy; app = krótko dodane do rotacji (lifetime)'
      selector:
        select:
          options: [notify, app]
      default: notify

    show_duration_s:
      name: Show duration (seconds)
      description: Ile sekund ma być widoczny komunikat.
      selector:
        number: {min: 1, max: 120, unit_of_measurement: s, mode: slider}
      default: 8

    app_lifetime_s:
      name: (app) Lifetime in queue (seconds)
      description: Jak długo appka „żyje” w kolejce (po wyświetleniu wygaśnie).
      selector:
        number: {min: 1, max: 300, unit_of_measurement: s, mode: slider}
      default: 20

    app_repeat:
      name: (app) Repeat count
      description: Ile razy pokazać w ramach jednej publikacji.
      selector:
        number: {min: 1, max: 5, mode: slider}
      default: 1

mode: single

variables:
  device_ids: !input awtrix

  # Pobranie device_topic z encji HA każdego wybranego urządzenia
  devices_base_topics: >-
    {%- macro get_device_topic(device_id) -%}
    {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro -%}
    {%- set ns = namespace(devs=[]) -%}
    {%- for device_id in device_ids -%}
      {%- set dev = get_device_topic(device_id) | replace(' ','') -%}
      {%- set ns.devs = ns.devs + [ dev ] -%}
    {%- endfor -%}
    {{ ns.devs }}

  power_sensor: !input power_source
  sensor_unit: !input sensor_unit

  # surowa wartość z sensora (kW lub W)
  raw_power: "{{ states[power_sensor].state | float(0) | abs }}"

  # znormalizowana moc do W (jeśli sensor kW -> *1000)
  power_level: >-
    {% if sensor_unit == 'kW' %}
      {{ (raw_power * 1000) | round(0) }}
    {% else %}
      {{ raw_power | round(0) }}
    {% endif %}

  threshold_low: !input threshold_low
  threshold_high: !input threshold_high

  power_level_icon: >-
    {%- if power_level | float > threshold_high | float -%}54156
    {%- elif power_level | float > threshold_low | float -%}50557
    {%- else -%}50546
    {%- endif -%}

  power_level_color: >-
    {%- if power_level | float > threshold_high | float -%}#04FE04
    {%- elif power_level | float > threshold_low | float -%}#FCFEFC
    {%- else -%}#FF4E1A
    {%- endif -%}

  # tekst: jeśli >= 1000 W, pokazujemy w kW
  power_level_text: >-
    {%- if (power_level | float) >= 1000 -%}
      {{ ((power_level | float) / 1000) | round(1) }} kW
    {%- else -%}
      {{ (power_level | float) | round(0) }} W
    {%- endif -%}

  skip_if_zero_watts: !input skip_if_zero_watts
  skip_during_night_hours: !input skip_during_night_hours

  display_mode: !input display_mode
  show_duration_s: !input show_duration_s
  app_lifetime_s: !input app_lifetime_s
  app_repeat: !input app_repeat

  # wybór suffixu topiku wg trybu
  topic_suffix: >-
    {% if display_mode == 'notify' %}/notify{% else %}/custom/solar_power{% endif %}

  # kompletne topiki per urządzenie
  devices_topics: >-
    {%- set ns = namespace(list=[]) -%}
    {%- for base in devices_base_topics -%}
      {%- set _ = ns.list.append(base ~ topic_suffix) -%}
    {%- endfor -%}
    {{ ns.list }}

  # PAYLOADY jako czyste stringi JSON (bez tojson, żeby # w kolorze nie psuł składni)
  payload_notify: >-
    {"icon":{{ power_level_icon }},"text":"{{ power_level_text }}","color":"{{ power_level_color }}","duration":{{ show_duration_s }},"repeat":1}

  payload_app: >-
    {"icon":{{ power_level_icon }},"text":"{{ power_level_text }}","color":"{{ power_level_color }}","duration":{{ show_duration_s }},"repeat":{{ app_repeat }},"lifetime":{{ app_lifetime_s }}}

  payload_final: >-
    {% if display_mode == 'notify' %}
      {{ payload_notify }}
    {% else %}
      {{ payload_app }}
    {% endif %}

  night_start: !input night_starts_after_time
  night_end: !input night_ends_after_time

trigger:
  - platform: time_pattern
    minutes: !input refresh_minutes

condition: []

action:
  - choose:
      - alias: "Skipping"
        conditions:
          - condition: template
            value_template: >
              {% set now_time = now().strftime("%H:%M") %}
              {{ (skip_during_night_hours and ((now_time < night_end) or (now_time > night_start))) or
                 (skip_if_zero_watts and (power_level | float == 0)) }}
        sequence:
          - repeat:
              for_each: "{{ devices_topics }}"
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: '{}'

      - alias: "Show (notify/app)"
        conditions: []
        sequence:
          - repeat:
              for_each: "{{ devices_topics }}"
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item }}"
                    payload: "{{ payload_final }}"
